# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"  


  - package-ecosystem: "npm"
    directory: "/Material.Blazor"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "sass"


  - package-ecosystem: "npm"
    directory: "/Material.Blazor.MD3"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "sass"


  - package-ecosystem: "npm"
    directory: "/Material.Blazor.Website"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "sass"


  - package-ecosystem: "npm"
    directory: "/Material.Blazor.Website.MD3"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "sass"



  - package-ecosystem: "nuget"
    directory: "/Material.Blazor"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "Microsoft.*"
        versions: ["8.x"]

  - package-ecosystem: "nuget"
    directory: "/Material.Blazor.Test"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "Microsoft.*"
        versions: ["8.x"]

  - package-ecosystem: "nuget"
    directory: "/Material.Blazor.Website"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "Nager.Date"
      - dependency-name: "Microsoft.*"
        versions: ["8.x"]

  - package-ecosystem: "nuget"
    directory: "/Material.Blazor.Website.Server"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "Microsoft.*"
        versions: ["8.x"]

  - package-ecosystem: "nuget"
    directory: "/Material.Blazor.Website.WebAssembly"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "Microsoft.*"
        versions: ["8.x"]



  - package-ecosystem: "nuget"
    directory: "/Material.Blazor.MD3"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/Material.Blazor.Website.MD3"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "Nager.Date"

  - package-ecosystem: "nuget"
    directory: "/Material.Blazor.Website.Server.MD3"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/Material.Blazor.Website.WebAssembly.MD3"
    schedule:
      interval: "weekly"
