<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<IsPackable>false</IsPackable>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="bunit" Version="2.11.3" />
		<PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.12" />
		<PackageReference Include="NSubstitute" Version="6.2.0" />
		<PackageReference Include="xunit.v3" Version="4.0.1" />
		<PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Material.Blazor\Material.Blazor.csproj" />
	</ItemGroup>
</Project>
