# Runs on the BlazorMdc.BlazorMdc.Master pipeline

trigger:
  branches:
    include:
      - master
    exclude:
      - develop

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release_Server'
  buildPlatform: 'Any CPU'
  project: 'BlazorMdc/BlazorMdc.csproj'

steps:

- powershell: 'dotnet build --configuration $(buildConfiguration) $(project)'
  displayName: 'Building $(project) in $(buildConfiguration) mode'

- powershell: 'dotnet pack --configuration $(buildConfiguration) --no-build --output $(Build.ArtifactStagingDirectory) $(project)'
  displayName: 'Generating nuget package'

- task: NuGetCommand@2
  displayName: 'Pushing NuGet package to internal feed'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'BlazorMdc'
    allowPackageConflicts: true
