# Runs on the BlazorMdc.BlazorMdc.Develop pipeline

trigger:
  branches:
    include:
    - develop
    exclude:
    - main

pr: 
  autoCancel: true
  branches:
    include:
    - develop
    exclude:
    - main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Debug_Server'
  buildPlatform: 'Any CPU'
  project: 'BlazorMdc/BlazorMdc.csproj'

steps:

- powershell: 'Write-Host "##vso[task.setvariable variable=ciSuffix]CI.$(Build.BuildNumber)"'
  displayName: 'Creating CI suffix with powershell'

- task: CmdLine@2
  displayName: "Displaying CI suffix"
  inputs:
    script: echo ciSuffix is $(ciSuffix)

- powershell: 'dotnet build --configuration $(buildConfiguration) $(project)'
  displayName: 'Building $(project) in $(buildConfiguration) mode'

- powershell: 'dotnet pack --configuration $(buildConfiguration) --no-build --output $(Build.ArtifactStagingDirectory) --version-suffix $(ciSuffix) $(project)'
  displayName: 'Generating nuget package'

- task: NuGetCommand@2
  displayName: 'Pushing NuGet package to internal feed'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'BlazorMdc'
    allowPackageConflicts: true
