@echo off
echo ...
echo ... Updating Material.Blazor
echo ...
cd material.blazor
call npm update -S
rem ***
cd ..\material.blazor.website
echo ...
echo ... Updating Material.Blazor.Website
echo ...
call npm update -S
rem ***
cd ..
rem echo ...
rem echo ... Updating docfx
rem echo ...
rem dotnet tool update -g docfx
rem ***
