@echo off
cd material.blazor
echo ...
echo ... Updating Material.Blazor
echo ...
call npm update -S
cd ..\material.blazor.md3
echo ...
echo ... Updating Material.Blazor.MD3
echo ...
call npm install @material/web@nightly
call npm update -S
cd ..
echo ...
echo ... Updating docfx
echo ...
dotnet tool update -g docfx
